TEMPLATE = app
CONFIG += console
CONFIG -= app_bundle
CONFIG -= qt

SOURCES += main.c \
    help.c

HEADERS += \
    include/protocol.h \
    include/mavlink_types.h \
    include/mavlink_protobuf_manager.hpp \
    include/mavlink_helpers.h \
    include/mavlink_conversions.h \
    include/checksum.h \
    include/common/version.h \
    include/common/testsuite.h \
    include/common/mavlink_msg_vision_speed_estimate.h \
    include/common/mavlink_msg_vision_position_estimate.h \
    include/common/mavlink_msg_vicon_position_estimate.h \
    include/common/mavlink_msg_vfr_hud.h \
    include/common/mavlink_msg_system_time.h \
    include/common/mavlink_msg_sys_status.h \
    include/common/mavlink_msg_statustext.h \
    include/common/mavlink_msg_state_correction.h \
    include/common/mavlink_msg_sim_state.h \
    include/common/mavlink_msg_set_roll_pitch_yaw_thrust.h \
    include/common/mavlink_msg_set_roll_pitch_yaw_speed_thrust.h \
    include/common/mavlink_msg_set_quad_swarm_roll_pitch_yaw_thrust.h \
    include/common/mavlink_msg_set_quad_swarm_led_roll_pitch_yaw_thrust.h \
    include/common/mavlink_msg_set_quad_motors_setpoint.h \
    include/common/mavlink_msg_setpoint_8dof.h \
    include/common/mavlink_msg_setpoint_6dof.h \
    include/common/mavlink_msg_set_mode.h \
    include/common/mavlink_msg_set_local_position_setpoint.h \
    include/common/mavlink_msg_set_gps_global_origin.h \
    include/common/mavlink_msg_set_global_position_setpoint_int.h \
    include/common/mavlink_msg_servo_output_raw.h \
    include/common/mavlink_msg_scaled_pressure.h \
    include/common/mavlink_msg_scaled_imu2.h \
    include/common/mavlink_msg_scaled_imu.h \
    include/common/mavlink_msg_safety_set_allowed_area.h \
    include/common/mavlink_msg_safety_allowed_area.h \
    include/common/mavlink_msg_roll_pitch_yaw_thrust_setpoint.h \
    include/common/mavlink_msg_roll_pitch_yaw_speed_thrust_setpoint.h \
    include/common/mavlink_msg_roll_pitch_yaw_rates_thrust_setpoint.h \
    include/common/mavlink_msg_request_data_stream.h \
    include/common/mavlink_msg_rc_channels_scaled.h \
    include/common/mavlink_msg_rc_channels_raw.h \
    include/common/mavlink_msg_rc_channels_override.h \
    include/common/mavlink_msg_raw_pressure.h \
    include/common/mavlink_msg_raw_imu.h \
    include/common/mavlink_msg_radio_status.h \
    include/common/mavlink_msg_ping.h \
    include/common/mavlink_msg_param_value.h \
    include/common/mavlink_msg_param_set.h \
    include/common/mavlink_msg_param_request_read.h \
    include/common/mavlink_msg_param_request_list.h \
    include/common/mavlink_msg_optical_flow.h \
    include/common/mavlink_msg_omnidirectional_flow.h \
    include/common/mavlink_msg_nav_controller_output.h \
    include/common/mavlink_msg_named_value_int.h \
    include/common/mavlink_msg_named_value_float.h \
    include/common/mavlink_msg_mission_write_partial_list.h \
    include/common/mavlink_msg_mission_set_current.h \
    include/common/mavlink_msg_mission_request_partial_list.h \
    include/common/mavlink_msg_mission_request_list.h \
    include/common/mavlink_msg_mission_request.h \
    include/common/mavlink_msg_mission_item_reached.h \
    include/common/mavlink_msg_mission_item.h \
    include/common/mavlink_msg_mission_current.h \
    include/common/mavlink_msg_mission_count.h \
    include/common/mavlink_msg_mission_clear_all.h \
    include/common/mavlink_msg_mission_ack.h \
    include/common/mavlink_msg_memory_vect.h \
    include/common/mavlink_msg_manual_setpoint.h \
    include/common/mavlink_msg_manual_control.h \
    include/common/mavlink_msg_log_request_list.h \
    include/common/mavlink_msg_log_request_end.h \
    include/common/mavlink_msg_log_request_data.h \
    include/common/mavlink_msg_log_erase.h \
    include/common/mavlink_msg_log_entry.h \
    include/common/mavlink_msg_log_data.h \
    include/common/mavlink_msg_local_position_setpoint.h \
    include/common/mavlink_msg_local_position_ned_system_global_offset.h \
    include/common/mavlink_msg_local_position_ned.h \
    include/common/mavlink_msg_hil_state_quaternion.h \
    include/common/mavlink_msg_hil_state.h \
    include/common/mavlink_msg_hil_sensor.h \
    include/common/mavlink_msg_hil_rc_inputs_raw.h \
    include/common/mavlink_msg_hil_optical_flow.h \
    include/common/mavlink_msg_hil_gps.h \
    include/common/mavlink_msg_hil_controls.h \
    include/common/mavlink_msg_highres_imu.h \
    include/common/mavlink_msg_heartbeat.h \
    include/common/mavlink_msg_gps_status.h \
    include/common/mavlink_msg_gps_raw_int.h \
    include/common/mavlink_msg_gps_inject_data.h \
    include/common/mavlink_msg_gps_global_origin.h \
    include/common/mavlink_msg_gps2_raw.h \
    include/common/mavlink_msg_global_vision_position_estimate.h \
    include/common/mavlink_msg_global_position_setpoint_int.h \
    include/common/mavlink_msg_global_position_int.h \
    include/common/mavlink_msg_file_transfer_start.h \
    include/common/mavlink_msg_file_transfer_res.h \
    include/common/mavlink_msg_file_transfer_dir_list.h \
    include/common/mavlink_msg_debug_vect.h \
    include/common/mavlink_msg_debug.h \
    include/common/mavlink_msg_data_stream.h \
    include/common/mavlink_msg_command_long.h \
    include/common/mavlink_msg_command_ack.h \
    include/common/mavlink_msg_change_operator_control_ack.h \
    include/common/mavlink_msg_change_operator_control.h \
    include/common/mavlink_msg_battery_status.h \
    include/common/mavlink_msg_auth_key.h \
    include/common/mavlink_msg_attitude_quaternion.h \
    include/common/mavlink_msg_attitude.h \
    include/common/mavlink.h \
    include/common/common.h \
    help.h

